<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["/"]["*"]="R";
$PERM["service"]["*"]="R";
$PERM["index.php"]["7"]="W";
$PERM["page.php"]["*"]="D";
$PERM["page.php"]["6"]="X";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
?>